# Generated by Django 2.0.3 on 2018-07-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_auto_20180720_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSuplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Suplier',
        ),
        migrations.AddField(
            model_name='product',
            name='suplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductSuplier'),
        ),
    ]
