# Generated by Django 2.0.3 on 2018-07-23 11:05

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20180723_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsuplier',
            name='curent_sum',
            field=django_prices.models.MoneyField(currency='RUB', decimal_places=2, default=0, max_digits=12),
        ),
    ]
