# Generated by Django 2.0.3 on 2018-07-24 04:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_productsuplier_curent_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=Decimal('999999'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
