# Generated by Django 2.0.3 on 2018-07-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', 'fix_empty_data_in_lines'),
        ('checkout', '0009_auto_20180720_1239'),
    ]

    operations = [
    ]
