# Generated by Django 2.0.3 on 2018-07-23 04:39

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20180723_1139'),
        ('order', '0049_auto_20180720_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_net', django_prices.models.MoneyField(currency='RUB', decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Не доставлено'), ('partially fulfilled', 'Частично доставлено'), ('fulfilled', 'Доставлено'), ('canceled', 'Отменено')], default='current', max_length=32)),
                ('suplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.ProductSuplier')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Не доставлено'), ('partially fulfilled', 'Частично доставлено'), ('fulfilled', 'Доставлено'), ('canceled', 'Отменено')], default='unfulfilled', max_length=32),
        ),
        migrations.AddField(
            model_name='orderline',
            name='suplierorder',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='order.SuplierOrder'),
        ),
    ]
