# Generated by Django 2.0.3 on 2018-07-23 04:39

from django.db import migrations, models
import django_countries.fields
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180718_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Может просматривать пользователей'), ('edit_user', 'Может редактировать пользователей'), ('view_staff', 'Может смотреть админов'), ('edit_staff', 'Может изменять админов'), ('impersonate_user', 'Может заходить от лица других пользователей'))},
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_area',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='company_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='Russian Federation', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_area',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_2',
            field=models.CharField(default='', max_length=256),
        ),
    ]
